[pytest]
DJANGO_SETTINGS_MODULE = playground_server.settings_test
python_files = test_*.py *_test.py
python_classes = Test*
python_functions = test_*
testpaths = blocks/tests
addopts =
    --cov=blocks.api_helpers
    --cov=blocks.encryption
    --cov-report=term-missing
    --cov-report=html:htmlcov
    --cov-fail-under=85
    -v
