# Generated by Django 4.2.7 on 2025-09-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0005_encrypt_existing_mnemonics'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(choices=[('upbit_btc', '업비트 비트코인'), ('upbit_usdt', '업비트 USDT'), ('bithumb', '빗썸'), ('okx', 'OKX'), ('binance', '바이낸스')], max_length=20, unique=True)),
                ('fee_rate', models.DecimalField(decimal_places=4, max_digits=6)),
                ('is_event', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['exchange'],
            },
        ),
    ]
