# Generated by Django 4.2.7 on 2025-09-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0006_exchangerate'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightningService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('boltz', 'Boltz Exchange'), ('coinos', 'Coinos')], max_length=20, unique=True)),
                ('fee_rate', models.DecimalField(decimal_places=4, max_digits=6)),
                ('description', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['service'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(choices=[('okx', 'OKX'), ('binance', '바이낸스')], max_length=20)),
                ('withdrawal_type', models.CharField(choices=[('onchain', '온체인'), ('lightning', '라이트닝')], max_length=20)),
                ('fee_btc', models.DecimalField(decimal_places=8, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['exchange', 'withdrawal_type'],
                'unique_together': {('exchange', 'withdrawal_type')},
            },
        ),
    ]
