# Generated by Django 4.2.7 on 2025-09-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0007_lightningservice_withdrawalfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightningservice',
            name='is_kyc',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lightningservice',
            name='service',
            field=models.CharField(choices=[('boltz', 'Boltz Exchange'), ('coinos', 'Coinos'), ('walletofsatoshi', '월렛오브사토시'), ('strike', 'Strike')], max_length=30, unique=True),
        ),
    ]
