# Generated by Django 4.2.7 on 2025-09-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0008_lightningservice_is_kyc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerate',
            name='event_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
