# Generated by Django 4.2.7 on 2025-09-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0009_exchangerate_event_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightningservice',
            name='is_custodial',
            field=models.BooleanField(default=True),
        ),
    ]
