# Generated by Django 4.2.7 on 2025-09-22 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0011_fix_boltz_custodial_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('user', '사용자'), ('upbit', '업비트'), ('bithumb', '빗썸'), ('binance', '바이낸스'), ('okx', 'OKX'), ('strike', 'Strike'), ('walletofsatoshi', '월렛오브사토시'), ('coinos', 'Coinos'), ('boltz', 'Boltz Exchange'), ('personal_wallet', '개인지갑')], max_length=30, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('is_kyc', models.BooleanField(default=False)),
                ('is_custodial', models.BooleanField(default=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['service'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_type', models.CharField(choices=[('trading', '거래수수료'), ('withdrawal_lightning', '라이트닝 출금'), ('withdrawal_onchain', '온체인 출금')], max_length=30)),
                ('fee_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('fee_fixed', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_to', to='blocks.servicenode')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_from', to='blocks.servicenode')),
            ],
            options={
                'ordering': ['source', 'destination', 'route_type'],
                'unique_together': {('source', 'destination', 'route_type')},
            },
        ),
    ]
