# Generated by Django 4.2.7 on 2025-09-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0015_mnemonic_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routingsnapshot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='servicenode',
            name='service',
            field=models.CharField(choices=[('user', '사용자'), ('upbit', '업비트'), ('upbit_krw', '업비트 원화'), ('upbit_btc', '업비트 BTC'), ('upbit_usdt', '업비트 USDT'), ('bithumb', '빗썸'), ('bithumb_krw', '빗썸 원화'), ('bithumb_btc', '빗썸 BTC'), ('bithumb_usdt', '빗썸 USDT'), ('binance', '바이낸스'), ('binance_usdt', '바이낸스 USDT'), ('binance_btc', '바이낸스 BTC'), ('okx', 'OKX'), ('okx_usdt', 'OKX USDT'), ('okx_btc', 'OKX BTC'), ('strike', 'Strike'), ('walletofsatoshi', '월렛오브사토시'), ('coinos', 'Coinos'), ('boltz', 'Boltz Exchange'), ('personal_wallet', '개인지갑')], max_length=30, unique=True),
        ),
    ]
