# Generated by Django 4.2.7 on 2025-10-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0016_alter_routingsnapshot_id_alter_servicenode_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='SidebarConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_mining', models.BooleanField(default=True)),
                ('show_wallet', models.BooleanField(default=True)),
                ('show_fee', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'blocks_sidebar_config',
            },
        ),
    ]
