# Generated by Django 4.2.7 on 2025-10-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0017_sidebarconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidebarconfig',
            name='show_utxo',
            field=models.BooleanField(default=True),
        ),
    ]
