# Generated by Django 4.2.7 on 2025-10-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0022_kingstonewallet_mnemonic'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='kingstonewallet',
            new_name='blocks_king_usernam_d25b15_idx',
            old_name='blocks_kingstone_username_idx',
        ),
        migrations.AlterField(
            model_name='kingstonewallet',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
