# Generated by Django 4.2.7 on 2025-10-19 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0023_rename_blocks_kingstone_username_idx_blocks_king_usernam_d25b15_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kingstonewallet',
            name='pin_encrypted',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
