# Generated by Django 4.2.7 on 2025-11-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0028_route_event_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceQueryCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('context_key', models.CharField(blank=True, default='', max_length=50)),
                ('start_year', models.PositiveSmallIntegerField()),
                ('end_year', models.PositiveSmallIntegerField()),
                ('series_data', models.JSONField()),
                ('fx_rate', models.DecimalField(decimal_places=4, default=1300, max_digits=10)),
                ('hit_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-hit_count', '-updated_at'],
                'indexes': [models.Index(fields=['query_key'], name='blocks_fina_query_k_bfa250_idx'), models.Index(fields=['context_key'], name='blocks_fina_context_09a006_idx'), models.Index(fields=['expires_at'], name='blocks_fina_expires_797659_idx')],
            },
        ),
    ]
