# Generated by Django 4.2.7 on 2025-11-28 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0029_financequerycache'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_identifier', models.CharField(blank=True, default='', max_length=255)),
                ('prompt', models.TextField()),
                ('quick_requests', models.JSONField(blank=True, default=list)),
                ('context_key', models.CharField(blank=True, default='', max_length=50)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, default='')),
                ('assets_count', models.PositiveSmallIntegerField(default=0)),
                ('processing_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='blocks_fina_created_bdc5eb_idx'), models.Index(fields=['user_identifier'], name='blocks_fina_user_id_cf5ae8_idx'), models.Index(fields=['success'], name='blocks_fina_success_427ca4_idx')],
            },
        ),
    ]
