# Generated by Django 4.2.7 on 2025-11-28 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0030_financequerylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_type', models.CharField(choices=[('intent_classifier', 'Intent Classifier Agent'), ('price_retriever', 'Price Retriever Agent'), ('calculator', 'Calculator Agent'), ('guardrail', 'Guardrail Agent')], db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('system_prompt', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['agent_type'],
                'indexes': [models.Index(fields=['agent_type'], name='blocks_agen_agent_t_a0ce3d_idx'), models.Index(fields=['is_active'], name='blocks_agen_is_acti_33e785_idx')],
            },
        ),
    ]
