# Generated by Django 4.2.26 on 2025-12-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0031_agentprompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceQuickRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150)),
                ('example', models.TextField(blank=True, default='')),
                ('quick_request', models.TextField()),
                ('context_key', models.CharField(blank=True, default='', max_length=50)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['sort_order'], name='blocks_fina_sort_or_2df7bd_idx'), models.Index(fields=['is_active'], name='blocks_fina_is_acti_57c142_idx')],
            },
        ),
    ]
