# Generated by Django 4.2.26 on 2025-12-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0032_financequickrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceQuickCompareGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=50, unique=True)),
                ('label', models.CharField(max_length=150)),
                ('assets', models.JSONField(blank=True, default=list)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['sort_order'], name='blocks_fina_sort_or_1216bd_idx'), models.Index(fields=['is_active'], name='blocks_fina_is_acti_bb3d40_idx')],
            },
        ),
    ]
