# Generated by Django 4.2.26 on 2025-12-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0033_financequickcomparegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='financequickcomparegroup',
            name='resolved_assets',
            field=models.JSONField(blank=True, default=list, help_text='Pre-resolved asset information with label, ticker, id, category'),
        ),
    ]
