# Generated by Django 4.2.26 on 2025-12-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0034_financequickcomparegroup_resolved_assets'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetPriceCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(db_index=True, help_text='Asset ticker or identifier', max_length=100)),
                ('label', models.CharField(help_text='Human-readable asset name', max_length=200)),
                ('category', models.CharField(blank=True, help_text='Asset category', max_length=100)),
                ('unit', models.CharField(default='USD', help_text='Price unit (USD, KRW, etc)', max_length=10)),
                ('source', models.CharField(blank=True, help_text='Data source', max_length=100)),
                ('yearly_prices', models.JSONField(default=dict, help_text='Yearly closing prices from 2009 onwards')),
                ('start_year', models.IntegerField(default=2009, help_text='First year of data')),
                ('end_year', models.IntegerField(help_text='Last year of data')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-last_updated'],
                'indexes': [
                    models.Index(fields=['asset_id'], name='blocks_asse_asset_i_b8e9f5_idx'),
                    models.Index(fields=['last_updated'], name='blocks_asse_last_up_c4a5e3_idx'),
                ],
                'unique_together': {('asset_id',)},
            },
        ),
    ]
