# Generated by Django 4.2.26 on 2025-12-13 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0036_sidebarconfig_show_finance'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='assetpricecache',
            new_name='blocks_asse_asset_i_6897e7_idx',
            old_name='blocks_asse_asset_i_b8e9f5_idx',
        ),
        migrations.RenameIndex(
            model_name='assetpricecache',
            new_name='blocks_asse_last_up_6ff264_idx',
            old_name='blocks_asse_last_up_c4a5e3_idx',
        ),
    ]
