# Generated by Django 4.2.7 on 2025-12-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0038_compatibilityagentprompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompatibilityAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField()),
                ('birth_time', models.TimeField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('element', models.CharField(max_length=10)),
                ('zodiac', models.CharField(max_length=20)),
                ('yin_yang', models.CharField(max_length=5)),
                ('score', models.IntegerField()),
                ('rating', models.CharField(max_length=50)),
                ('narrative', models.TextField()),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='compatibilityagentprompt',
            new_name='blocks_comp_agent_k_80d893_idx',
            old_name='blocks_comp_agent_k_17717e_idx',
        ),
        migrations.RenameIndex(
            model_name='compatibilityagentprompt',
            new_name='blocks_comp_is_acti_a8e4e7_idx',
            old_name='blocks_comp_is_acti_8224ad_idx',
        ),
        migrations.AlterField(
            model_name='compatibilityagentprompt',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='compatibilityanalysis',
            index=models.Index(fields=['-created_at'], name='blocks_comp_created_703d65_idx'),
        ),
        migrations.AddIndex(
            model_name='compatibilityanalysis',
            index=models.Index(fields=['user_ip'], name='blocks_comp_user_ip_b6cab3_idx'),
        ),
    ]
