# Generated by Django 4.2.7 on 2025-12-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0045_compatibilityquickpreset_description'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='compatibilityquickpreset',
            new_name='blocks_comp_is_acti_62dd21_idx',
            old_name='blocks_com_is_acti_f9de5b_idx',
        ),
        migrations.AlterField(
            model_name='compatibilityquickpreset',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
