# Generated by Django 4.2.7 on 2025-12-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0046_rename_blocks_com_is_acti_f9de5b_idx_blocks_comp_is_acti_62dd21_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compatibilityquickpreset',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
