# Generated by Django 4.2.7 on 2025-12-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0047_alter_compatibilityquickpreset_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compatibilityagentprompt',
            name='model_name',
            field=models.CharField(default='gemini-2.5-flash', max_length=100),
        ),
    ]
