# Generated by Django 4.2.26 on 2025-12-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0049_update_quick_presets_vitalik'),
    ]

    operations = [
        migrations.AddField(
            model_name='compatibilityagentprompt',
            name='frequency_penalty',
            field=models.FloatField(default=0.4),
        ),
        migrations.AddField(
            model_name='compatibilityagentprompt',
            name='max_tokens',
            field=models.IntegerField(default=700),
        ),
        migrations.AddField(
            model_name='compatibilityagentprompt',
            name='presence_penalty',
            field=models.FloatField(default=0.6),
        ),
        migrations.AddField(
            model_name='compatibilityagentprompt',
            name='temperature',
            field=models.FloatField(default=0.2),
        ),
        migrations.AddField(
            model_name='compatibilityagentprompt',
            name='top_p',
            field=models.FloatField(default=0.9),
        ),
    ]
