# Generated by Django 4.2.7 on 2025-12-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0050_compatibilityagentprompt_frequency_penalty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compatibilityagentprompt',
            name='model_name',
            field=models.CharField(default='openai:gpt-5-mini', max_length=100),
        ),
    ]
