# Generated by Django 4.2.7 on 2025-12-16 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0054_timecapsule'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecapsule',
            name='mnemonic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_capsules', to='blocks.mnemonic'),
        ),
    ]
