# Generated by Django 4.2.26 on 2025-12-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0055_timecapsule_mnemonic'),
    ]

    operations = [
        migrations.AddField(
            model_name='compatibilityquickpreset',
            name='stored_saju',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='timecapsule',
            name='bitcoin_address',
            field=models.CharField(default='', max_length=100),
        ),
    ]
