# Generated by Django 4.2.26 on 2025-12-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0056_compatibilityquickpreset_stored_saju_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compatibilityquickpreset',
            name='stored_saju',
            field=models.TextField(blank=True, default=''),
        ),
    ]
