# Generated by Django 4.2.7 on 2025-12-17 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0057_alter_compatibilityquickpreset_stored_saju'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compatibilityquickpreset',
            name='stored_saju',
        ),
    ]
