# Generated by Django 4.2.7 on 2025-12-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0066_update_report_templates_tone'),
    ]

    operations = [
        migrations.AddField(
            model_name='mnemonic',
            name='next_address_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='timecapsule',
            name='address_index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
