# Generated by Django 4.2.7 on 2025-12-19 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0067_compatibilityagentcache'),
        ('blocks', '0070_timecapsulebroadcastsetting'),
    ]

    operations = [
    ]
