# Generated by Django 4.2.7 on 2025-12-21 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0072_timecapsule_broadcast_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timecapsulebroadcastsetting',
            options={'verbose_name': 'Time Capsule Broadcast Setting', 'verbose_name_plural': 'Time Capsule Broadcast Settings'},
        ),
        migrations.RenameIndex(
            model_name='compatibilityagentcache',
            new_name='blocks_comp_categor_490c32_idx',
            old_name='blocks_comp_category_0c2b59_idx',
        ),
        migrations.RenameIndex(
            model_name='compatibilityagentcache',
            new_name='blocks_comp_subject_d0fddc_idx',
            old_name='blocks_comp_subject_172a70_idx',
        ),
        migrations.RenameIndex(
            model_name='compatibilityagentcache',
            new_name='blocks_comp_target__e44da2_idx',
            old_name='blocks_comp_target__a9e5a2_idx',
        ),
        migrations.RenameIndex(
            model_name='compatibilityagentcache',
            new_name='blocks_comp_updated_059bda_idx',
            old_name='blocks_comp_updated_6e8ba1_idx',
        ),
        migrations.AlterField(
            model_name='compatibilityagentcache',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='compatibilityreporttemplate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
