# Generated by Django 4.2.7 on 2025-12-21 01:22

from django.db import migrations, models


def safe_remove_old_indexes(apps, schema_editor):
    """Safely remove old indexes if they exist"""
    try:
        # Check if the table exists first
        with schema_editor.connection.cursor() as cursor:
            if schema_editor.connection.vendor == 'sqlite':
                cursor.execute("""
                    SELECT name FROM sqlite_master
                    WHERE type='table' AND name='blocks_compatibilityagentcache'
                """)
                if not cursor.fetchone():
                    return  # Table doesn't exist, skip

                # Get all indexes on the table
                cursor.execute("""
                    SELECT name FROM sqlite_master
                    WHERE type='index' AND tbl_name='blocks_compatibilityagentcache'
                """)
                existing_indexes = {row[0] for row in cursor.fetchall()}

                # Drop old indexes if they exist
                old_indexes = [
                    'blocks_comp_category_0c2b59_idx',
                    'blocks_comp_subject_172a70_idx',
                    'blocks_comp_target__a9e5a2_idx',
                    'blocks_comp_updated_6e8ba1_idx',
                ]
                for index_name in old_indexes:
                    if index_name in existing_indexes:
                        cursor.execute(f'DROP INDEX {index_name}')
            else:
                # PostgreSQL/MySQL: Use DROP INDEX IF EXISTS
                old_indexes = [
                    'blocks_comp_category_0c2b59_idx',
                    'blocks_comp_subject_172a70_idx',
                    'blocks_comp_target__a9e5a2_idx',
                    'blocks_comp_updated_6e8ba1_idx',
                ]
                for index_name in old_indexes:
                    try:
                        cursor.execute(f'DROP INDEX IF EXISTS {index_name}')
                    except Exception:
                        pass  # Ignore if index doesn't exist
    except Exception as e:
        # If anything goes wrong, just continue - new indexes will be created
        print(f"Warning: Could not remove old indexes: {e}")


def safe_add_new_indexes(apps, schema_editor):
    """Safely add new indexes if they don't exist"""
    try:
        with schema_editor.connection.cursor() as cursor:
            if schema_editor.connection.vendor == 'sqlite':
                # Get existing indexes
                cursor.execute("""
                    SELECT name FROM sqlite_master
                    WHERE type='index' AND tbl_name='blocks_compatibilityagentcache'
                """)
                existing_indexes = {row[0] for row in cursor.fetchall()}

                # Add new indexes if they don't exist
                new_indexes = {
                    'blocks_comp_categor_490c32_idx': 'CREATE INDEX blocks_comp_categor_490c32_idx ON blocks_compatibilityagentcache (category)',
                    'blocks_comp_subject_d0fddc_idx': 'CREATE INDEX blocks_comp_subject_d0fddc_idx ON blocks_compatibilityagentcache (subject_name)',
                    'blocks_comp_target__e44da2_idx': 'CREATE INDEX blocks_comp_target__e44da2_idx ON blocks_compatibilityagentcache (target_name)',
                    'blocks_comp_updated_059bda_idx': 'CREATE INDEX blocks_comp_updated_059bda_idx ON blocks_compatibilityagentcache (updated_at)',
                }
                for index_name, create_sql in new_indexes.items():
                    if index_name not in existing_indexes:
                        cursor.execute(create_sql)
            else:
                # PostgreSQL/MySQL: Use CREATE INDEX IF NOT EXISTS (PostgreSQL) or check first
                new_indexes = {
                    'blocks_comp_categor_490c32_idx': 'CREATE INDEX blocks_comp_categor_490c32_idx ON blocks_compatibilityagentcache (category)',
                    'blocks_comp_subject_d0fddc_idx': 'CREATE INDEX blocks_comp_subject_d0fddc_idx ON blocks_compatibilityagentcache (subject_name)',
                    'blocks_comp_target__e44da2_idx': 'CREATE INDEX blocks_comp_target__e44da2_idx ON blocks_compatibilityagentcache (target_name)',
                    'blocks_comp_updated_059bda_idx': 'CREATE INDEX blocks_comp_updated_059bda_idx ON blocks_compatibilityagentcache (updated_at)',
                }
                for index_name, create_sql in new_indexes.items():
                    try:
                        cursor.execute(create_sql)
                    except Exception:
                        pass  # Index already exists
    except Exception as e:
        print(f"Warning: Could not add new indexes: {e}")


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0072_timecapsule_broadcast_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timecapsulebroadcastsetting',
            options={'verbose_name': 'Time Capsule Broadcast Setting', 'verbose_name_plural': 'Time Capsule Broadcast Settings'},
        ),
        # Remove old indexes if they exist (safe removal)
        migrations.RunPython(
            safe_remove_old_indexes,
            reverse_code=migrations.RunPython.noop,
        ),
        # Add new indexes if they don't exist (safe addition)
        migrations.RunPython(
            safe_add_new_indexes,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='compatibilityagentcache',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='compatibilityreporttemplate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
