# Generated by Django 4.2.23 on 2025-12-21 02:00
# Modified: use DROP INDEX IF EXISTS so this is idempotent on partial-apply state.

from django.db import migrations


def _drop_if_exists(name):
    return migrations.RunSQL(
        sql=f"DROP INDEX IF EXISTS {name};",
        reverse_sql=migrations.RunSQL.noop,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0073_alter_timecapsulebroadcastsetting_options_and_more'),
    ]

    operations = [
        _drop_if_exists('blocks_comp_category_0c2b59_idx'),
        _drop_if_exists('blocks_comp_subject_172a70_idx'),
        _drop_if_exists('blocks_comp_target__a9e5a2_idx'),
        _drop_if_exists('blocks_comp_updated_6e8ba1_idx'),
    ]
