# Generated by Django 4.2.23 on 2025-12-21 02:02
# Modified: use CREATE INDEX IF NOT EXISTS so this is idempotent on partial-apply state.

from django.db import migrations


def _add_if_not_exists(index_name, table, column):
    return migrations.RunSQL(
        sql=f"CREATE INDEX IF NOT EXISTS {index_name} ON {table} ({column});",
        reverse_sql=f"DROP INDEX IF EXISTS {index_name};",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0074_remove_compatibilityagentcache_blocks_comp_category_0c2b59_idx_and_more'),
    ]

    operations = [
        _add_if_not_exists('blocks_comp_categor_490c32_idx', 'blocks_compatibilityagentcache', 'category'),
        _add_if_not_exists('blocks_comp_subject_d0fddc_idx', 'blocks_compatibilityagentcache', 'subject_name'),
        _add_if_not_exists('blocks_comp_target__e44da2_idx', 'blocks_compatibilityagentcache', 'target_name'),
        _add_if_not_exists('blocks_comp_updated_059bda_idx', 'blocks_compatibilityagentcache', 'updated_at'),
    ]
