# Generated by Django 4.2.23 on 2025-12-21 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0074_sidebarconfig_show_compatibility_timecapsule'),
        ('blocks', '0075_compatibilityagentcache_blocks_comp_categor_490c32_idx_and_more'),
    ]

    operations = [
    ]
