# Generated by Django 4.2.23 on 2025-12-23 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0075_financequickcomparegroup_auto_sync_enabled'),
        ('blocks', '0076_merge_20251221_2206'),
    ]

    operations = [
    ]
