# Generated by Django 4.2.7 on 2026-01-03 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0076_financequerylog_is_prefetch'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceQueryAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(blank=True, default='', max_length=100)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('ticker', models.CharField(blank=True, default='', max_length=100)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='financequerylog',
            name='prompt',
        ),
        migrations.RemoveField(
            model_name='financequerylog',
            name='quick_requests',
        ),
        migrations.AddField(
            model_name='financequeryasset',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_rows', to='blocks.financequerylog'),
        ),
        migrations.AddIndex(
            model_name='financequeryasset',
            index=models.Index(fields=['asset_id'], name='blocks_fina_asset_i_5463b5_idx'),
        ),
        migrations.AddIndex(
            model_name='financequeryasset',
            index=models.Index(fields=['label'], name='blocks_fina_label_ca6360_idx'),
        ),
        migrations.AddIndex(
            model_name='financequeryasset',
            index=models.Index(fields=['ticker'], name='blocks_fina_ticker_963297_idx'),
        ),
    ]
