# Generated by Django 4.2.7 on 2026-01-03 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0077_financequeryasset_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='compatibilityagentcache',
            new_name='blocks_comp_categor_490c32_idx',
            old_name='blocks_comp_category_0c2b59_idx',
        ),
        migrations.RenameIndex(
            model_name='compatibilityagentcache',
            new_name='blocks_comp_subject_d0fddc_idx',
            old_name='blocks_comp_subject_172a70_idx',
        ),
        migrations.RenameIndex(
            model_name='compatibilityagentcache',
            new_name='blocks_comp_target__e44da2_idx',
            old_name='blocks_comp_target__a9e5a2_idx',
        ),
        migrations.RenameIndex(
            model_name='compatibilityagentcache',
            new_name='blocks_comp_updated_059bda_idx',
            old_name='blocks_comp_updated_6e8ba1_idx',
        ),
    ]
