# Generated by Django 4.2.7 on 2026-01-03 06:50
# Modified: conditional SQL so this is a no-op on fresh databases where
# migrations 0074a/0075a already removed and recreated these indexes.

from django.db import migrations


def _rename_if_exists(old_name, new_name):
    def forward(apps, schema_editor):
        if schema_editor.connection.vendor != 'postgresql':
            return
        schema_editor.execute(
            f"ALTER INDEX IF EXISTS {old_name} RENAME TO {new_name};"
        )

    return migrations.RunPython(forward, migrations.RunPython.noop)


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0077_financequeryasset_and_more'),
    ]

    operations = [
        _rename_if_exists('blocks_comp_category_0c2b59_idx', 'blocks_comp_categor_490c32_idx'),
        _rename_if_exists('blocks_comp_subject_172a70_idx', 'blocks_comp_subject_d0fddc_idx'),
        _rename_if_exists('blocks_comp_target__a9e5a2_idx', 'blocks_comp_target__e44da2_idx'),
        _rename_if_exists('blocks_comp_updated_6e8ba1_idx', 'blocks_comp_updated_059bda_idx'),
    ]
