# Generated by Django 4.2.23 on 2026-01-03 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0077_merge_20251223_2154'),
        ('blocks', '0078_rename_blocks_comp_category_0c2b59_idx_blocks_comp_categor_490c32_idx_and_more'),
    ]

    operations = [
    ]
