from django.urls import path, re_path
from . import views, timecapsule

urlpatterns = [
    path('status', views.status_view, name='status'),
    path('blocks', views.blocks_view, name='blocks'),
    path('mine', views.mine_view, name='mine'),
    path('stream', views.stream_view, name='stream'),
    path('finance/historical-returns', views.finance_historical_returns_view, name='finance_historical_returns'),
    path('finance/yearly-closing-prices', views.finance_yearly_closing_prices_view, name='finance_yearly_closing_prices'),
    path('finance/custom-asset/resolve', views.finance_resolve_custom_asset_view, name='finance_resolve_custom_asset'),
    path('finance/quick-requests', views.finance_quick_requests_view, name='finance_quick_requests'),
    path('finance/quick-compare-groups', views.finance_quick_compare_groups_view, name='finance_quick_compare_groups'),
    path('finance/price-cache', views.finance_price_cache_view, name='finance_price_cache'),
    # Accept both with/without trailing slash
    re_path(r'^register_nick/?$', views.register_nick_view, name='register_nick'),
    re_path(r'^check_nick/?$', views.check_nick_view, name='check_nick'),
    re_path(r'^init_reset/?$', views.init_reset_view, name='init_reset'),
    # Mnemonic endpoints
    path('mnemonic/request', views.request_mnemonic_view, name='request_mnemonic'),
    path('mnemonic/generate', views.generate_mnemonic_view, name='generate_mnemonic'),
    path('mnemonic/save', views.save_mnemonic_view, name='save_mnemonic'),
    path('mnemonic/admin', views.admin_mnemonics_view, name='admin_mnemonics'),
    path('mnemonic/balance', views.mnemonic_balance_view, name='mnemonic_balance'),
    path('mnemonic/admin/balance', views.admin_set_mnemonic_balance_view, name='admin_mnemonic_balance'),
    path('mnemonic/balance/onchain', views.mnemonic_onchain_balance_view, name='mnemonic_onchain_balance'),
    path('mnemonic/admin/delete', views.admin_delete_mnemonic_view, name='admin_delete_mnemonic'),
    path('mnemonic/admin/xpub', views.admin_mnemonic_xpub_view, name='admin_mnemonic_xpub'),
    path('mnemonic/admin/address', views.admin_mnemonic_address_view, name='admin_mnemonic_address'),
    path('mnemonic/admin/unassign', views.admin_unassign_mnemonic_view, name='admin_mnemonic_unassign'),
    path('mnemonic/validate', views.validate_mnemonic_view, name='validate_mnemonic'),
    # Exchange rate endpoints
    path('exchange-rates', views.exchange_rates_view, name='exchange_rates'),
    path('exchange-rates/admin', views.admin_exchange_rates_view, name='admin_exchange_rates'),
    # Withdrawal fee endpoints
    path('withdrawal-fees', views.withdrawal_fees_view, name='withdrawal_fees'),
    path('withdrawal-fees/admin', views.admin_withdrawal_fees_view, name='admin_withdrawal_fees'),
    # Lightning service endpoints
    path('lightning-services', views.lightning_services_view, name='lightning_services'),
    path('lightning-services/admin', views.admin_lightning_services_view, name='admin_lightning_services'),
    # New routing system endpoints
    path('service-nodes/admin', views.admin_service_nodes_view, name='admin_service_nodes'),
    path('routes/admin', views.admin_routes_view, name='admin_routes'),
    path('optimal-paths', views.get_optimal_paths_view, name='optimal_paths'),
    path('routing-snapshot', views.routing_snapshot_view, name='routing_snapshot'),
    # Sidebar config endpoints
    path('sidebar-config', views.sidebar_config_view, name='sidebar_config'),
    path('sidebar-config/admin', views.admin_update_sidebar_config_view, name='admin_sidebar_config'),
    # Kingstone wallet endpoints
    path('kingstone/wallets', views.kingstone_wallets_view, name='kingstone_wallets'),
    path('kingstone/pin/verify', views.kingstone_verify_pin_view, name='kingstone_verify_pin'),
    path('kingstone/pin/register', views.kingstone_register_pin_view, name='kingstone_register_pin'),
    path('kingstone/wallet/delete', views.kingstone_delete_wallet_view, name='kingstone_delete_wallet'),
    path('kingstone/wallet/address', views.kingstone_wallet_address_view, name='kingstone_wallet_address'),
    path('kingstone/admin/wallets', views.admin_kingstone_wallets_view, name='admin_kingstone_wallets'),
    # Wallet password
    path('wallet/password/admin', views.admin_set_wallet_password_view, name='admin_set_wallet_password'),
    path('wallet/password/check', views.wallet_password_check_view, name='wallet_password_check'),
    path('wallet/password/admin/get', views.admin_get_wallet_password_view, name='admin_get_wallet_password'),
    # Compatibility agent prompt
    path('compatibility/prompt', views.compatibility_prompt_view, name='compatibility_prompt'),
    path('compatibility/admin/prompt', views.compatibility_admin_prompt_view, name='compatibility_admin_prompt'),
    path('compatibility/agent/generate', views.compatibility_agent_generate_view, name='compatibility_agent_generate'),
    path('compatibility/report-templates', views.compatibility_report_templates_view, name='compatibility_report_templates'),
    path('compatibility/admin/report-templates/<str:key>', views.compatibility_admin_report_template_detail_view, name='compatibility_admin_report_template_detail'),
    path('compatibility/quick-presets', views.compatibility_quick_presets_view, name='compatibility_quick_presets'),
    path('compatibility/admin/quick-presets', views.compatibility_admin_quick_presets_view, name='compatibility_admin_quick_presets'),
    path('compatibility/admin/quick-presets/<int:pk>', views.compatibility_admin_quick_preset_detail_view, name='compatibility_admin_quick_preset_detail'),
    path('compatibility/admin/cache', views.compatibility_agent_cache_list_view, name='compatibility_agent_cache_list'),
    path('compatibility/admin/cache/<int:pk>', views.compatibility_agent_cache_detail_view, name='compatibility_agent_cache_detail'),
    # Compatibility analysis endpoints
    path('compatibility/analysis/save', views.compatibility_analysis_save_view, name='compatibility_analysis_save'),
    path('compatibility/analysis/list', views.compatibility_analysis_list_view, name='compatibility_analysis_list'),
    # Finance management endpoints
    path('finance/admin/logs', views.admin_finance_logs_view, name='admin_finance_logs'),
    path('finance/admin/stats', views.admin_finance_stats_view, name='admin_finance_stats'),
    # Agent prompt management endpoints
    path('finance/admin/agent-prompts', views.admin_agent_prompts_view, name='admin_agent_prompts'),
    path('finance/admin/agent-prompts/<str:agent_type>', views.admin_agent_prompt_detail_view, name='admin_agent_prompt_detail'),
    path('finance/admin/quick-requests', views.admin_finance_quick_requests_view, name='admin_finance_quick_requests'),
    path('finance/admin/quick-requests/<int:pk>', views.admin_finance_quick_request_detail_view, name='admin_finance_quick_request_detail'),
    path('finance/admin/quick-compare-groups', views.admin_finance_quick_compare_groups_view, name='admin_finance_quick_compare_groups'),
    path('finance/admin/quick-compare-groups/<int:pk>', views.admin_finance_quick_compare_group_detail_view, name='admin_finance_quick_compare_group_detail'),
    path('finance/admin/price-cache', views.admin_price_cache_view, name='admin_price_cache'),
    path('finance/admin/price-cache/<int:pk>', views.admin_price_cache_detail_view, name='admin_price_cache_detail'),
    # Time Capsule endpoints
    path('time-capsule/save', timecapsule.time_capsule_save_view, name='time_capsule_save'),
    path('time-capsule/admin/list', timecapsule.admin_time_capsules_view, name='admin_time_capsules'),
    path('time-capsule/admin/mnemonic', timecapsule.admin_time_capsule_mnemonic_view, name='admin_time_capsule_mnemonic'),
    path('time-capsule/admin/broadcast-settings', timecapsule.admin_time_capsule_broadcast_settings_view, name='admin_time_capsule_broadcast_settings'),
    path('time-capsule/admin/broadcast-test', timecapsule.admin_time_capsule_broadcast_test_view, name='admin_time_capsule_broadcast_test'),
    path('time-capsule/admin/build-tx', timecapsule.admin_time_capsule_build_transaction_view, name='admin_time_capsule_build_tx'),
    path('time-capsule/admin/xpub', timecapsule.admin_time_capsule_xpub_view, name='admin_time_capsule_xpub'),
    path('time-capsule/admin/xpub/balance', timecapsule.admin_time_capsule_xpub_balance_view, name='admin_time_capsule_xpub_balance'),
    path('time-capsule/admin/broadcast-tx', timecapsule.admin_time_capsule_broadcast_transaction_view, name='admin_time_capsule_broadcast_tx'),
    path('time-capsule/admin/broadcast-record/<int:pk>', timecapsule.admin_time_capsule_record_broadcast_view, name='admin_time_capsule_record_broadcast'),
    path('time-capsule/admin/fee-estimates', timecapsule.admin_time_capsule_fee_estimates_view, name='admin_time_capsule_fee_estimates'),
    path('time-capsule/admin/assign-address/<int:pk>', timecapsule.admin_time_capsule_assign_address_view, name='admin_time_capsule_assign_address'),
    path('time-capsule/admin/unassign-address/<int:pk>', timecapsule.admin_time_capsule_unassign_address_view, name='admin_time_capsule_unassign_address'),
    path('time-capsule/admin/update-coupon/<int:pk>', timecapsule.admin_time_capsule_update_coupon_view, name='admin_time_capsule_update_coupon'),
    path('time-capsule/admin/delete/<int:pk>', timecapsule.admin_time_capsule_delete_view, name='admin_time_capsule_delete'),
]
